// <auto-generated />
using System;
using MechanicalDms.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MechanicalDms.Database.Migrations
{
    [DbContext(typeof(DmsDbContext))]
    [Migration("20210706130644_Add-Cracked-Player")]
    partial class AddCrackedPlayer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MechanicalDms.Database.Models.BilibiliUser", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.Property<int>("GuardLevel")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("BilibiliUser", "mechanical_dms");
                });

            modelBuilder.Entity("MechanicalDms.Database.Models.DiscordUser", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Element")
                        .HasColumnType("int");

                    b.Property<string>("IdentifyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGuard")
                        .HasColumnType("bit");

                    b.Property<string>("MinecraftPlayerUuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.HasIndex("MinecraftPlayerUuid");

                    b.ToTable("DiscordUser", "mechanical_dms");
                });

            modelBuilder.Entity("MechanicalDms.Database.Models.KaiheilaUser", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("BilibiliUserUid")
                        .HasColumnType("bigint");

                    b.Property<string>("IdentifyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinecraftPlayerUuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.HasIndex("BilibiliUserUid");

                    b.HasIndex("MinecraftPlayerUuid");

                    b.ToTable("KaiheilaUser", "mechanical_dms");
                });

            modelBuilder.Entity("MechanicalDms.Database.Models.MDAuthCrackedPlayer", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uuid");

                    b.ToTable("MDAuthCrackedPlayer", "mechanical_dms");
                });

            modelBuilder.Entity("MechanicalDms.Database.Models.MinecraftPlayer", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsLegitCopy")
                        .HasColumnType("bit");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uuid");

                    b.ToTable("MinecraftPlayer", "mechanical_dms");
                });

            modelBuilder.Entity("MechanicalDms.Database.Models.DiscordUser", b =>
                {
                    b.HasOne("MechanicalDms.Database.Models.MinecraftPlayer", "MinecraftPlayer")
                        .WithMany()
                        .HasForeignKey("MinecraftPlayerUuid");

                    b.Navigation("MinecraftPlayer");
                });

            modelBuilder.Entity("MechanicalDms.Database.Models.KaiheilaUser", b =>
                {
                    b.HasOne("MechanicalDms.Database.Models.BilibiliUser", "BilibiliUser")
                        .WithMany()
                        .HasForeignKey("BilibiliUserUid");

                    b.HasOne("MechanicalDms.Database.Models.MinecraftPlayer", "MinecraftPlayer")
                        .WithMany()
                        .HasForeignKey("MinecraftPlayerUuid");

                    b.Navigation("BilibiliUser");

                    b.Navigation("MinecraftPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
